name: Deploy MkopoSuite Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3

      - name: 🟢 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install Dependencies
        run: npm install

      - name: ⚙️ Run Sequelize Migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx sequelize-cli db:migrate
